### PR TITLE
Added static registration for http tracers to allow matching change in envoy.

### PR DESCRIPTION
**Pull request by mrice32**

### CODE REVIEW

**Comment by htuch** [comment]
As discussed offline, we'll need to figure out a backwards compatibility story for this change per policy at https://github.com/lyft/envoy/blob/master/CONTRIBUTING.md#breaking-change-policy

**Comment by mrice32** [comment]
Do we want to leave this example repo using the deprecated filter API until the next release?  If this repository is generally used as an example for new users wanting to extend filters, we might want to prepare any them for the API change ahead of time.  If it's only really used for CI, this may be less important since the envoy repository already has adequate testing for the new filter factories.  Alternatively, we could add a second example for the new API and mention that the other one is deprecated.

**Comment by htuch** [comment]
Let's move it to the new API. Can you update the PR to match the name changes for the new API?

**Comment by mrice32** [comment]
Will do.  We still want this PR to be against the envoy-ci branch, right?

**Pull request merged**
